#!/bin/bash
#
# Enter the JuypterLab virtualenv and invoke the Python entry point created by
# rubin.nublado.startup to start JupyterLab.

source /usr/local/share/jupyterlab/venv/bin/activate
exec nublado-start-lab
