FROM python:3.13.7-slim-trixie
# Install uv.
COPY --from=ghcr.io/astral-sh/uv:0.9.0 /uv /bin/uv

COPY fsadmin/screenrc /root/.screenrc
COPY fsadmin/scripts/install-packages /tmp
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    /tmp/install-packages && rm /tmp/install-packages
RUN chsh -s /bin/bash root

USER 0:0
WORKDIR /tmp
ENV SHELL="/bin/bash"
CMD [ "tail", "-f", "/dev/null" ]
