#!/usr/bin/env bash
set -x

set -euo pipefail

# First system

vi_dir="/usr/local/share/jupyterlab/versions-installed"
mkdir -p ${vi_dir}
cd ${vi_dir}
dpkg -l | tee "system-dpkgs"
pip list | tee "system-python"

# Now JupyterLab python

source /usr/local/share/jupyterlab/venv/bin/activate
pip list | tee "jupyterlab-python"
# This started failing 16 May 2025.  Under investigation.
((jupyter labextension list 2>&1) | tee "lab-extensions" ) || /bin/true
deactivate


