#!/usr/bin/env bash
set -x

# Bash "strict mode", to help catch problems and bugs in the shell
# script. Every bash script you write should include this. See
# http://redsymbol.net/articles/unofficial-bash-strict-mode/ for
# details.
set -euo pipefail

# Tell apt-get we're never going to be able to give manual
# feedback:
export DEBIAN_FRONTEND=noninteractive

# Install various dependencies for runtime.

# git: required by setuptools_scm
# git-lfs: required for new user setup in lsst-rsp
# pandoc: get the dependencies the venv nbconvert will need
# texlive*: export to PDF
# jq ... bzip2: useful utilities
# man: it is an interactive system, after all
# curl: CLI http client is useful
# nano ... ed: enough editors to cover most people's habits
#  (I gave up on emacs in the base container, alas)
apt-get -y install --no-install-recommends \
    git git-lfs pandoc \
    texlive-latex-recommended texlive-plain-generic \
    texlive-fonts-recommended texlive-pstricks texlive-luatex texlive-xetex \
    jq gh hub unzip ack screen tmux tree file less xz-utils bzip2 \
    man curl \
    nano vim ed
