#!/usr/bin/env bash
set -x
set -euo pipefail

# This is for Fritz, and my nefarious plan to make the "te" in "Jupyter" TECO.
# We switched from TECOC to Paul Koning's Python implementation because it
#  simplifies installation a bit.  I doubt anyone is going to complain.

src=/usr/local/share/git
mkdir -p ${src}
cd ${src}
git clone https://github.com/lsst-sqre/pyteco.git
install -m 0755 pyteco/teco.py /usr/local/bin/teco

# The default terminal colors look bad in light mode.
git clone https://github.com/lsst-sqre/dircolors-solarized.git
cp dircolors-solarized/dircolors* /etc

# Install typst.  It's not packaged for Debian, but there are binary releases
# available on its GitHub page.

# Get the tags; throw away the calver attempt and any rc tags;
# extract the most recent version.
#
# This is fragile, and we can always replace it with a static version
# if we need to.  However, since the practice of the DM stack, which we've
# adopted in the mechanisms surrounding the stack, is to float and not
# pin versions insofar as possible (and thereby deal with major-version
# breakage as it happens), we're doing that here too and trying to just
# quietly take the most recent release we can find.
typst_ver=$(
    git ls-remote --tags --refs --sort="-version:refname" \
    https://github.com/typst/typst | \
    grep -v "v23\-03\-" | \
    grep -v "\-rc" | \
    head -1 | \
    awk '{print $2}' | \
    sed -e 's|refs/tags/||'
	 )

# Download the appropriate archive
fname="typst-$(arch)-unknown-linux-musl.tar.xz"
url="https://github.com/typst/typst/releases/download/${typst_ver}/${fname}"
curl -L "${url}" > typst.tar.xz

tar x --strip-components=1 -vf typst.tar.xz
install -m 0755 typst /usr/local/bin/typst

# Install agents for use by jupyter-ai

mkdir -p /tmp/agents
cd /tmp/agents
curl -fsSL "https://claude.ai/install.sh" > claude-install.sh
bash -x ./claude-install.sh
# Claude does not make it easy to modify where it lands.
cd $HOME/.local/share
mv claude /usr/local/share
cd /usr/local/share/claude/versions
latest_ver=$(ls -1 | tail -1)  # There should only ever be one anyway.
ln -s /usr/local/share/claude/versions/${latest_ver} /usr/local/bin/claude

curl -fsSL https://gh.io/copilot-install > copilot-install.sh
bash -x ./copilot-install.sh

npm i -g @agentclientprotocol/claude-agent-acp
npm i -g @zed-industries/codex-acp
npm i -g @openai/codex
npm i -g @google/gemini-cli

cd /
rm -rf /tmp/agents
