#!/usr/bin/env bash
set -x

# This script installs additional packages used by the dependency image but
# not needed by the runtime image, such as additional packages required to
# build Python dependencies.
#
# Since the base image wipes all the apt caches to clean up the image that
# will be reused by the runtime image, we unfortunately have to do another
# apt-get update here, which wastes some time and network.

# Bash "strict mode", to help catch problems and bugs in the shell
# script. Every bash script you write should include this. See
# http://redsymbol.net/articles/unofficial-bash-strict-mode/ for
# details.
set -euo pipefail

# Tell apt-get we're never going to be able to give manual
# feedback:
export DEBIAN_FRONTEND=noninteractive

# Update the package listing, so we know what packages exist:
apt-get update

# Install various dependencies for runtime.

# git: required by setuptools_scm
# pandoc: get the dependencies the venv nbconvert will need
# jq ... less: useful utilities
# man: it is an interactive system, after all
# curl: CLI http client is useful
# nano ... ed: enough editors to cover most people's habits
#  (I gave up on emacs in the base container, alas)
apt-get -y install --no-install-recommends \
    git pandoc \
    jq gh hub unzip ack screen tmux tree file less \
    man curl \
    nano vim ed
