#!/usr/bin/env bash
set -x
set -euo pipefail

# This doesn't really belong here, but this script runs inside the build
# environment, which is where we want to put npm.
#
# Install the various node-based protocol servers and CLIs.

npm i -g @agentclientprotocol/claude-agent-acp
npm i -g @zed-industries/codex-acp
npm i -g @openai/codex
npm i -g @google/gemini-cli

# Install Jupyterlab and its runtime extensions in its own virtualenv
# (not the Stack python).  This will let us iterate the UI without having
# to worry about stack compatibility.
uv venv /usr/local/share/jupyterlab/venv

# Use that venv.
source /usr/local/share/jupyterlab/venv/bin/activate

# Install the rubin.nublado.startup module and the JupyterLab dependency
# group.
uv sync --frozen --active --inexact --no-default-groups --compile-bytecode \
    --no-editable --group lab

# File sharing doesn't work in the RSP environment; remove the extension.
jupyter labextension disable "@jupyterlab/filebrowser-extension:share-file"

# Jupyter News is just obnoxious.
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

# Our RSP menu supersedes the Hub menu items
jupyter labextension disable "@jupyterlab/hub-extension:menu"

# Lock those extensions to prevent reenabling.
jupyter labextension lock "@jupyterlab/hub-extension:menu" \
	"@jupyterlab/apputils-extension:announcements" \
	"@jupyterlab/filebrowser-extension:share-file"

# Clean up cache
uv cache clean
