#!/usr/bin/env bash
set -x
set -euo pipefail

# Install Jupyterlab and its runtime extensions in its own virtualenv
# (not the Stack python).  This will let us iterate the UI without having
# to worry about stack compatibility.
uv venv /usr/local/share/jupyterlab/venv

# Use that venv.
source /usr/local/share/jupyterlab/venv/bin/activate

# Install the set of packages we need for the RSP JupyterLab UI
# jupyter_firefly_extensions is slightly incompatible with bokeh
uv pip install --upgrade \
   astrowidgets \
   black-nb \
   bqplot \
   datashader \
   firefly-client \
   geoviews \
   holoviews \
   ipydatawidgets \
   ipython-genutils \
   ipympl \
   ipyvolume \
   ipyvuetify \
   ipywebrtc \
   ipywidgets \
   jupyter \
   jupyter_firefly_extensions \
   jupyter-resource-usage \
   jupyter-server \
   jupyter-server-proxy \
   jupyter_bokeh \
   jupyterhub \
   jupyterlab \
   jupyterlab_execute_time \
   jupyterlab_iframe \
   jupyterlab_widgets \
   lckr-jupyterlab-variableinspector \
   lsst-rsp \
   nbconvert \
   nbdime \
   nbval \
   panel \
   plotly \
   pythreejs \
   'git+https://github.com/lsst-sqre/rsp-jupyter-extensions@tickets/DM-53706' \
   sidecar

# File sharing doesn't work in the RSP environment; remove the extension.
jupyter labextension disable "@jupyterlab/filebrowser-extension:share-file"

# Jupyter News is just obnoxious.
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

# Our RSP menu supersedes the Hub menu items
jupyter labextension disable "@jupyterlab/hub-extension:menu"

# Lock those extensions to prevent reenabling.
jupyter labextension lock "@jupyterlab/hub-extension:menu" \
	"@jupyterlab/apputils-extension:announcements" \
	"@jupyterlab/filebrowser-extension:share-file"

# Clean up cache
uv cache clean

# Increase this to force a rebuild because a dependency package has changed.
# Reset when you actually change a package or its pins.
# Serial: 0

