#!/usr/bin/env bash
set -x

# This script installs additional packages used by the runtime image.

# Bash "strict mode", to help catch problems and bugs in the shell
# script. Every bash script you write should include this. See
# http://redsymbol.net/articles/unofficial-bash-strict-mode/ for
# details.
set -euo pipefail

# Tell apt-get we're never going to be able to give manual
# feedback:
export DEBIAN_FRONTEND=noninteractive

# Update the package listing, so we know what packages exist:
apt-get update

# Install various dependencies for runtime.

# git: required by setuptools_scm
# git-lfs: required for new user setup in lsst-rsp
# pandoc: get the dependencies the venv nbconvert/PDF export will need
# jq ... less: useful utilities
# man: it is an interactive system, after all
# curl: CLI http client is useful
# nano ... ed: enough editors to cover most people's habits
#  (I gave up on emacs in the base container, alas)
apt-get -y install --no-install-recommends \
    git git-lfs pandoc \
    jq gh hub unzip xz-utils ack screen tmux tree file less \
    man curl \
    nano vim ed

# Install the nodesource PPA; the nodejs that ships with Trixie is 20.x.
# It's July 2026 at the time of writing.
# 20.x is already EOL as of March 2026.
# 26 is good until at least July 2027.

curl https://deb.nodesource.com/setup_26.x -o setup_26_x.bash
bash ./setup_26_x.bash

# Nodejs is needed for Gemini and Codex agents, and LLM Chat doesn't work
# right for Codex and Claude without npm installed at runtime;
# I think this is something to do with entrypoint magic.
# The Nodesource nodejs rolls in npm (it's separate for stock debian)

apt-get update
apt-get -y install nodejs
