#!/usr/bin/env bash
set -x
set -euo pipefail

# This is for Fritz, and my nefarious plan to make the "te" in "Jupyter" TECO.
# We switched from TECOC to Paul Koning's Python implementation because it
#  simplifies installation a bit.  I doubt anyone is going to complain.

src=/usr/local/share/git
mkdir -p ${src}
cd ${src}
git clone https://github.com/lsst-sqre/pyteco.git
install -m 0755 pyteco/teco.py /usr/local/bin/teco

# The default terminal colors look bad in light mode.
git clone https://github.com/lsst-sqre/dircolors-solarized.git
cp dircolors-solarized/dircolors* /etc

# Install agents for use by jupyter-ai

mkdir -p /tmp/agents
cd /tmp/agents
curl -fsSL "https://claude.ai/install.sh" > claude-install.sh
bash -x ./claude-install.sh
# Claude does not make it easy to modify where it lands.
cd $HOME/.local/share
mv claude /usr/local/share
cd /usr/local/share/claude/versions
latest_ver=$(ls -1 | tail -1)  # There should only ever be one anyway.
ln -s /usr/local/share/claude/versions/${latest_ver} /usr/local/bin/claude

curl -fsSL https://gh.io/copilot-install > copilot-install.sh
bash -x ./copilot-install.sh

cd /
rm -rf /tmp/agents
