#!/usr/bin/env bash
set -x

# This script installs additional packages used by the runtime image.

# Bash "strict mode", to help catch problems and bugs in the shell
# script. Every bash script you write should include this. See
# http://redsymbol.net/articles/unofficial-bash-strict-mode/ for
# details.
set -euo pipefail

# Tell apt-get we're never going to be able to give manual
# feedback:
export DEBIAN_FRONTEND=noninteractive

# Update the package listing, so we know what packages exist:
apt-get update

# Install various dependencies for runtime.

# git: required by setuptools_scm
# git-lfs: required for new user setup in lsst-rsp
# pandoc: get the dependencies the venv nbconvert/PDF export will need
# jq ... less: useful utilities
# man: it is an interactive system, after all
# curl: CLI http client is useful
# nano ... ed: enough editors to cover most people's habits
#  (I gave up on emacs in the base container, alas)
apt-get -y install --no-install-recommends \
    git git-lfs pandoc \
    jq gh hub unzip xz-utils ack screen tmux tree file less \
    man curl \
    nano vim ed
