#!/usr/bin/env bash
set -x
set -euo pipefail

# Create user and home directory.
stackdir=/opt/lsst/software/stack
mkdir -p $stackdir
groupadd -g 1000 jovyan
grpconv
useradd -u 1000 -g 1000 -d $stackdir -s /bin/bash jovyan
pwconv

# We're going to want other directories there too.
chown -R jovyan:jovyan $(dirname $stackdir)
