#!/usr/bin/env bash
set -x
set -euo pipefail

# Create user and home directory.
homedir=/home/jovyan
mkdir -p $homedir
groupadd -g 1000 jovyan
grpconv
useradd -u 1000 -g 1000 -d $homedir -s /bin/bash jovyan
pwconv
