sequenceDiagram
  participant webdav
  participant browser
  participant controller
  participant kubernetes
  browser->>+controller: GET /files
  controller->>+kubernetes: create resources
  controller-)kubernetes: watch pod status
  create participant fileserver
  kubernetes->fileserver: create pod
  kubernetes--)-controller: pod started
  controller-->>-browser: 200

  webdav->>+fileserver: WebDAV request
  fileserver-->>-webdav: WebDAV response
