# Prune unreferenced Docker images and ticket branches from more than six
# months ago, weekly on Monday.

name: GHCR Cleanup

"on":
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: docker
      queue: max

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-orphaned-images: true
          delete-tags: "tickets-*,t-*"
          delete-untagged: true
          older-than: "6 months"
          packages: nublado
          validate: true

      - name: Report status
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "GHCR cleanup for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}

  cleanup-jupyterhub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: docker-jupyterhub
      queue: max

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-orphaned-images: true
          delete-tags: "tickets-*,t-*"
          delete-untagged: true
          older-than: "6 months"
          packages: nublado-jupyterhub
          validate: true

      - name: Report status
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "GHCR cleanup for {repo} (jupyterhub) failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}

  cleanup-jupyterlab:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: docker-jupyterlab
      queue: max

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-orphaned-images: true
          delete-tags: "tickets-*,t-*"
          delete-untagged: true
          older-than: "6 months"
          packages: nublado-jupyterlab-base
          validate: true

      - name: Report status
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "GHCR cleanup for {repo} (jupyterlab-base) failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}
