# This is a separate run of the Python test suite that doesn't cache the tox
# environment and runs from a schedule. The purpose is to test whether
# updating pinned dependencies would cause any tests to fail.

name: Periodic CI

"on":
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        python:
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      # Use the oldest supported version of Python to update dependencies,
      # not the matrixed Python version, since this accurately reflects
      # how dependencies should later be updated.

      - uses: lsst-sqre/run-nox@main
        with:
          nox-sessions: "upgrade-deps typing test"
          python-version: ${{ matrix.python }}
          use-cache: false

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Periodic test for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}

  # The controller requires Python 3.11, but the modules we add to the Hub
  # have to run with Python 3.10 since that's what the JupyterHub image uses.
  # Run a separate matrix to test those modules.
  test-hub:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [test]

    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - uses: lsst-sqre/run-nox@main
        with:
          nox-sessions: "upgrade-deps typing-hub test-hub"
          python-version: ${{ matrix.python }}
          use-cache: false

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Periodic test for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}
